#---
repos:
#
#-
#  repo: https://github.com/ambv/black
#  rev: 20.8b1
#  hooks:
#    -
#      id: black
#      language_version: python3
#
#-   repo: local
#    hooks:
#    -   id: python-tests
#        name: pytests
#        entry: pytest src/tests
#        language: python
#        additional_dependencies: [pre-commit, pytest, pandas, sklearn, matplotlib]
#        always_run: true
#        pass_filenames: false
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.8
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
      types: [python]
    # Run the formatter.
    - id: ruff-format
      types: [python]