name: Python Package and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:  [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python '3.8'
      uses: actions/setup-python@v3
      with:
        python-version:'3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Add project directory to PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
    - name: Test with pytest
      run: |
        pytest
#    - name: Python Black
#      run: |
#        black . --check
